# Purpose: HOME 대시보드 LOB 표·차트의 픽셀 치수를 정의한다.

"""HOME 대시보드 LOB 표·차트의 픽셀 치수를 정의한다."""

from __future__ import annotations

DASHBOARD_SCROLLBAR_HEIGHT_PX = 15

DASHBOARD_SECTION_GAP_PX = 16

DASHBOARD_TITLE_HEIGHT_PX = 44

DASHBOARD_TITLE_GAP_PX = 8

LOB_TABLE_HEADER_HEIGHT_PX = 45

LOB_DENSITY_ROW_HEIGHT_PX = 36

LOB_WAFER_PLAN_ROW_HEIGHT_PX = 36

LOB_WAFER_CAPA_ROW_HEIGHT_PX = 36

LOB_TABLE_ROW_HEIGHTS_PX = (
    LOB_TABLE_HEADER_HEIGHT_PX,
    LOB_DENSITY_ROW_HEIGHT_PX,
    LOB_WAFER_PLAN_ROW_HEIGHT_PX,
    LOB_WAFER_CAPA_ROW_HEIGHT_PX,
)

LOB_TABLE_HEIGHT_PX = sum(LOB_TABLE_ROW_HEIGHTS_PX)

LOB_CHART_HEIGHT_PX = 150

LOB_TOP5_HEIGHT_PX = 150

LOB_BOTTOM_MARGIN_PX = 130

LOB_FIGURE_HEIGHT_PX = (
    DASHBOARD_TITLE_HEIGHT_PX
    + LOB_TABLE_HEIGHT_PX
    + LOB_CHART_HEIGHT_PX
    + LOB_TOP5_HEIGHT_PX
    + LOB_BOTTOM_MARGIN_PX
)
