CREATE TABLE IF NOT EXISTS raw_data.core_data (
    dataset_id VARCHAR NOT NULL,
    source_row_no BIGINT NOT NULL,
    row_hash VARCHAR NOT NULL,
    "시뮬레이션 ID" VARCHAR,
    "PLAN ID" VARCHAR,
    "기준정보년월" BIGINT,
    "제품타입" VARCHAR,
    "U/PKG" VARCHAR,
    "UsreFamily3" VARCHAR,
    "Family4" VARCHAR,
    "U/6" VARCHAR,
    "PKG1" VARCHAR,
    "SITE" VARCHAR,
    "Area Class" VARCHAR,
    "Module/comp" VARCHAR,
    "LOB Code" VARCHAR,
    "PKG Part No" VARCHAR,
    "Capa Code" VARCHAR,
    "제품정보" VARCHAR,
    "생산계획년월" BIGINT,
    "생산수량" DOUBLE,
    "Stack" VARCHAR,
    "Customer" VARCHAR,
    "Pack Code" VARCHAR,
    "S/H" VARCHAR,
    "CS" VARCHAR,
    "D_EQ" BIGINT,
    "WF 구분" VARCHAR,
    "구분_Chip" BIGINT,
    "구분_EQ" BIGINT,
    "Chip수" BIGINT,
    "Plan_Chip(K개)" DOUBLE,
    "CHIP" BIGINT,
    "Net Die" BIGINT,
    "Month" BIGINT,
    "계획(K개)" DOUBLE,
    "8H 환산 계획(K개)" DOUBLE,
    "WF수(매)" DOUBLE,
    "PCB수(K매)" DOUBLE,
    "EQ(억Gb)" DOUBLE,
    "누락여부" VARCHAR,
    "계획기초정보여부" VARCHAR,
    "FAB" VARCHAR,
    "Area_Name" VARCHAR,
    "공정" VARCHAR,
    "메이커" VARCHAR,
    "STEP_SEQ" VARCHAR,
    "MCP_SEQ" VARCHAR,
    "모델명" VARCHAR,
    "Para" VARCHAR,
    "Step수" VARCHAR,
    "CAPA_RUN_RATE" DOUBLE,
    "소요기준" VARCHAR,
    "RUN_DAY" BIGINT,
    "일 필요" DOUBLE,
    "UPEH" DOUBLE,
    "ST" DOUBLE,
    "Lot 측정률" DOUBLE,
    "WF측정률" DOUBLE,
    "EDS_수율" DOUBLE,
    "BE_수율" DOUBLE,
    "CUM_수율" DOUBLE,
    "GOOD_DIE" DOUBLE,
    "TEST WF수(매)" DOUBLE,
    "Shot Time" VARCHAR,
    "Shot수" VARCHAR,
    "Index Time" VARCHAR,
    "모듈수" BIGINT,
    "Side반영률" BIGINT,
    "편중률" DOUBLE,
    "설비보유" DOUBLE,
    "설비대수변화관리" VARCHAR,
    "설비대여평가" DOUBLE,
    "설비대여평가항목" VARCHAR,
    "설비대여평가DESC" VARCHAR,
    "MCP_Chip_Ratio" BIGINT,
    "소요대수" DOUBLE,
    "시뮬레이션 누락여부" VARCHAR,
    "설비보유HCB" BIGINT,
    "CUSTOM" VARCHAR,
    "BONDING" VARCHAR,
    PRIMARY KEY (dataset_id, source_row_no)
);
